<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ACUQNDS" failures="0" tests="5" name="insuranceBase.TestBase" time="0.010" errors="1" timestamp="2024-07-21T20:05:27 IST" skipped="4">
  <testcase classname="insuranceBase.TestBase" name="urls" time="0.000">
    <skipped/>
  </testcase> <!-- urls -->
  <system-out/>
  <testcase classname="insuranceBase.TestBase" name="getbrowser" time="0.010">
    <error message="Cannot invoke &quot;Object.hashCode()&quot; because &quot;key&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at java.base/java.util.Properties.getProperty(Properties.java:1122)
at insuranceBase.TestBase.getbrowser(TestBase.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- getbrowser -->
  <system-out/>
  <testcase classname="insuranceBase.TestBase" name="userNames" time="0.000">
    <skipped/>
  </testcase> <!-- userNames -->
  <system-out/>
  <testcase classname="insuranceBase.TestBase" name="passwords" time="0.000">
    <skipped/>
  </testcase> <!-- passwords -->
  <system-out/>
  <testcase classname="insuranceBase.TestBase" name="readProperty" time="0.000">
    <skipped/>
  </testcase> <!-- readProperty -->
  <system-out/>
</testsuite> <!-- insuranceBase.TestBase -->
